### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by LuigiElleBalotta** [CypherCore/CypherCore#1]
Logging with my credentials:

username: test@test
psw: test

What happen?
You have been disconnected (BLZ51901021) 

I have used WoW_Patched.exe + cypher_bundle.txt

**Comment by hondacrx** [comment]
did you create the account with worldsever?  cant use the account command from TC has to be from the cyphercore server

**Comment by LuigiElleBalotta** [comment]
I have created the account from the cyphercore's worldserver console, isnt' it right?

.bnet create ecc....

**Comment by hondacrx** [comment]
what's the bnet server say?  if nothing then you have your wtf file set to connect to localhost?

**Comment by LuigiElleBalotta** [comment]
the bnet is only updating realmlist.. and yes i have set the wtf to localhost... 
Now i try using your commits and see if the problem is solved... 
(BTW why don't we use a common repo?)

**Comment by LuigiElleBalotta** [comment]
https://github.com/CypherCore/CypherCore/commit/bedfbd46e818fe8267f067585d873c0929728e93

I updated until here but no way to log in... You can log in with your repo?

**Comment by LuigiElleBalotta** [comment]
Don't know if it's relative to this issue but:

1. Start BnetServer from visual studio (right click on bnet project -> debug -> start)
2. open wow client
3. insert credentials
4. receive the error BLZ51901021
5. close wow client
6. close bnetserver window
7. this exception is shown (sorry it's italian because i have visual studio italian version):

Assistente al debug gestito 'CallbackOnCollectedDelegate' : 'Effettuato callback sul delegato 'Framework!Framework.Runtime.EventHandler::Invoke' raccolto nel Garbage Collector. È possibile che si verifichino blocchi dell'applicazione, danni e la perdita dei dati. Durante il passaggio al codice non gestito, i delegati devono essere mantenuti attivi dall'applicazione gestita fino a quando non sarà garantito che non verranno mai chiamati.'



This exception only occurs if you try to log in inside wow client. 
If you simply start / end bnetserver without use wow client, no exception raises.

**Comment by LuigiElleBalotta** [comment]
The second time that i try to log in i also get this ( i had to set a breakpoint on line 69 of SocketManager class) :

   in System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   in System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   in System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   in System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   in System.Activator.CreateInstance(Type type, Object[] args)
   in Framework.Networking.SocketManager`1.OnSocketOpen(Socket sock) in C:\Users\luigib\Documents\Visual Studio 2017\Projects\MyCypherCore\Framework\Networking\SocketManager.cs:riga 72

**Comment by hondacrx** [comment]
I know why your not logging in,  i forgot to add the certificate for bnet

Try https://github.com/CypherCore/CypherCore/commit/c30d6b50c8c9d9c177692b3ff0b6a476f3f69ff1
