### ISSUE TITLE
[Suggestion] More updated TrinityCore core

### ISSUE THREAD

**Issue by LuigiElleBalotta** [CypherCore/CypherCore#11]
Why don't use this core as reference instead of official trinitycore? 
https://github.com/AshamaneProject/AshamaneCore

**Comment by PadreWoW** [comment]
C# compiles with 1 Minute and 30 Seconds!
C++ (TrinityCore) with 40 Minutes!

**Comment by LuigiElleBalotta** [comment]
in fact, this repository is porting c++ code to c# from trinitycore. I suggest, instead of trinitycore of using AshamaneCore

**Comment by hondacrx** [comment]
feel free to use stuff from there to add them as a pull request,  just make sure to test it out.

**Comment by LuigiElleBalotta** [comment]
sure, but for something complex i need to be helped so i hope i won't be the only one to do that

**Comment by Denominator13** [comment]
Exactly what sqls do I need to upload in mysql? I'm assuming base folder for auth and characters but what are the other folders, I see updates folder with a lot of sql files. I am really liking this simply because it's C# and not C++

**Comment by hondacrx** [comment]
@Denominator13 Check readme.  if still need help check discord

**Comment by Denominator13** [comment]
Okay well I'm having an issue with BNetServer.exe it just keeps saying "updating realm list"?

**Comment by hondacrx** [comment]
@Denominator13 That is not a issue,  its working fine then.

**Comment by Denominator13** [comment]
Ahhh appreiated :) Still no idea which sqls to add though, I added auth and characters from base folder but now I'm lost lol

**Comment by hondacrx** [comment]
you need to download the full database from trinity core, then put them into the sql folder and let the world server do the rest

**Comment by Denominator13** [comment]
Ahhhh okay thank you :)

**Comment by Denominator13** [comment]
Which one should I download?

**Comment by hondacrx** [comment]
look in the updated readme https://github.com/CypherCore/CypherCore/blob/master/README.md :)

**Comment by Denominator13** [comment]
Okay so my worldserver.exe crashed
[WorldServer.log](https://github.com/CypherCore/CypherCore/files/1649704/WorldServer.log)

Nevermind I missed the conf part of directing to the folders lol

**Comment by Fabi** [comment]
Please don't use the issue tracker for support

**Comment by Denominator13** [comment]
Can't use discord it's telling me invite isn't valid

**Comment by Denominator13** [comment]
World.exe isn't finding db.2 files?

**Comment by LuigiElleBalotta** [comment]
rename the folder to enUS

**Comment by Denominator13** [comment]
Nah still the same :/

**Comment by Fabi** [comment]
God damn discord.... It was set to never expire, new one: https://discord.gg/Hac3qn6

**Comment by Denominator13** [comment]
Thank you Fabi :)
