### ISSUE TITLE
No client to download

### ISSUE THREAD

**Issue by PadreWoW** [CypherCore/CypherCore#12]
How to use

    Simply compile the solution as you do with TC c++ version.
    Download full TC's DB and place into folder. Use the updates that you can find in this repo.
    Edit BnetServer and WorldServer config files giving at least your Database Informations
    Must use Arctium WoW Client Launcher Download

Arctium WoW Client no longer available

**Comment by hondacrx** [comment]
fixed in https://github.com/CypherCore/CypherCore/commit/d2ff8683aed508a8e29cb24198ecdba547176165

**Comment by ReyDonovan** [comment]
64 bit system?
