### ISSUE TITLE
[BUG] The core let's you create more than one character at a time

### ISSUE THREAD

**Issue by LuigiElleBalotta** [CypherCore/CypherCore#2]
![cattura](https://user-images.githubusercontent.com/16773213/27636393-a3f6980e-5c0b-11e7-8dfa-bcf2b502bfea.PNG)

While creating a character, i pressed two times the button to complete the character creation and that's the result.

**Comment by hondacrx** [comment]
Known bug with TC also. Looking into how we can fix it.
