### ISSUE TITLE
Non english client crash

### ISSUE THREAD

**Issue by zqgmzq** [CypherCore/CypherCore#25]
enUS client works
But if set in Config.wtf
SET textLocale "ruRU"
SET audioLocale "ruRU"
or another lang
Client crash with error
It use too much memory
All ram used and client crash

**Comment by zqgmzq** [comment]
![img_20190101_134430](https://user-images.githubusercontent.com/45689766/50577718-07e5c680-0e37-11e9-8b6b-960bb28af621.jpg)
![img_20190101_134454](https://user-images.githubusercontent.com/45689766/50577721-159b4c00-0e37-11e9-986a-afb90a601dc3.jpg)

**Comment by hondacrx** [comment]
enable packet loggin and give me the cypher.pkt file or parse it with TC and display the parsed file here.

**Comment by zqgmzq** [comment]
[Logs_CypherCore.zip](https://github.com/CypherCore/CypherCore/files/2719834/Logs_CypherCore.zip)
