### ISSUE TITLE
Error extract core data (CypherTool)

### ISSUE THREAD

**Issue by ayell** [CypherCore/CypherCore#28]
Hi,
When i want extract all data on WoW (8.2.5) with the tools, I have this error :

Unhandled Exception: DataExtractor.CASCLib.BLTEDecoderException: unknown keyname 1CDAF3931871BEC3

I try to debug but I dont understand why when I go in this line I have this error ...

![image](https://user-images.githubusercontent.com/15988065/69651253-156bf680-1070-11ea-896e-f51ed97b008f.png)

![image](https://user-images.githubusercontent.com/15988065/69651565-93300200-1070-11ea-971e-2d5b050d1d72.png)

I tried to set the game language in french / English , same thing...

If someone can help me

**Comment by hondacrx** [comment]
Extractor is not updated to 8.2.5

**Comment by min-vison** [comment]
So there are any issues to run this server ?
