### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by kakukkokkal** [CypherCore/CypherCore#45]
During compilation:
/source/Source/Game/Chat/Commands/QuestCommands.cs(162,50): error CS0117: 'RBACPermissions' does not contain a definition for 'CommandQuestObjectiveComplete' [/source/Source/Game/Game.csproj]
revision f2cf016c61d007f83f49dd62532a72803f7325b0

**Comment by kakukkokkal** [comment]
I've worked around to add a value into RBACPermissions, but most probably an incorrect one.

**Comment by hondacrx** [comment]
Yeah i had it working  but have other changes in that file and didnt see the one change i needed to push.  pushed it now
