### ISSUE TITLE
Uncaught exception while loading C# scripts

### ISSUE THREAD

**Issue by iblameandrew** [CypherCore/CypherCore#49]
Got an error while executing WorldServer. 

Core builds DBs just fine, but crashes while preparing DataStorage.  Lots of red warnings about unused and/or undefined stuff aswell. It's also worth  mentioning that beforehand, the executables wouldn't point at the root directory. So to get to this point i had to paste a lot of stuff from the root, to the build folder.

System.Exception
  HResult=0x80131500
  Mensaje = AddScript
  Origen = Framework
  Seguimiento de la pila:
   en Cypher.Assert(Boolean value, String message, String memberName) en C:\Users\andres\Documents\repos\CypherCore-master\Source\Framework\Debugging\Errors.cs: línea 32
   en Game.Scripting.ScriptRegistry`1.AddScript(TValue script) en C:\Users\andres\Documents\repos\CypherCore-master\Source\Game\Scripting\ScriptManager.cs: línea 1290
   en Game.Scripting.ScriptManager.AddScript[T](T script) en C:\Users\andres\Documents\repos\CypherCore-master\Source\Game\Scripting\ScriptManager.cs: línea 1223
   en Game.Scripting.CreatureScript..ctor(String name) en C:\Users\andres\Documents\repos\CypherCore-master\Source\Game\Scripting\CoreScripts.cs: línea 325
   en Game.Scripting.GenericCreatureScript`1..ctor(String name, Object[] args) en C:\Users\andres\Documents\repos\CypherCore-master\Source\Game\Scripting\CoreScripts.cs: línea 305

In an attempt to solve this issue, i moved the Scripts folder from the Source folder to the Build directory, but it all seems pointless without a path reference to where the core is looking up the C# scripts. Any clues on how could i fix this would be much appreciated.

![report](https://user-images.githubusercontent.com/68928438/193478867-d8d59fd0-1df0-4323-992a-483b34ad2850.png)

**Comment by hondacrx** [comment]
Fixed in https://github.com/CypherCore/CypherCore/commit/4cd461bb956c26bc1a109ae78d017c3eb77514d1
