### ISSUE TITLE
this Crash happens when I launch the Server

### ISSUE THREAD

**Issue by HerokDeV** [CypherCore/CypherCore#53]
Crash to lift WodlServer
![Crash](https://user-images.githubusercontent.com/123419223/218589863-7347b8db-2ce2-43e8-ba10-d7d8e05a1f57.png)

**Comment by ZaDarkSide** [comment]
![image](https://user-images.githubusercontent.com/291278/218627660-092d7017-5751-4e63-8c05-c6289d34be36.png)

Change in file `Source/Game/Globals/ObjectManager.cs` at line `6552` as in the screenshot.
It should fix your problem.
