### ISSUE TITLE
How to create account

### ISSUE THREAD

**Issue by Nerus87** [CypherCore/CypherCore#56]
Hey, how I can create an account without updating DB manually?

**Comment by Fabi** [comment]
trinitycore wiki should tell you

**Comment by Nerus87** [comment]
Yeah, but not supporting MariaDB

**Comment by Fabi** [comment]
> Yeah, but not supporting MariaDB

Does not change anything. Everything else in the wiki still applies :D

**Comment by Nerus87** [comment]
![image](https://github.com/CypherCore/CypherCore/assets/3099926/b88de960-72ec-48c4-82e5-8c3151615d3f)

**Comment by ZaDarkSide** [comment]
To create a new account use this command in WorldServer: `bnetaccount create Player@Email YourPassword` then you can login with the email and password you just entered.

TrinityCore Wiki is here: https://trinitycore.info

**Comment by Nerus87** [comment]
Using MariaDB
![image](https://github.com/CypherCore/CypherCore/assets/3099926/d666d248-3ee6-4c40-a445-1ea112bc49c6)

**Comment by Fabi** [comment]
then use cypher…

**Comment by Nerus87** [comment]
I can't type in WorldServer.exe, probably all of SQL updates needs to finish executing.

**Comment by ZaDarkSide** [comment]
After WorldServer finishes loading everything then it can receive commands and you can type.

**Comment by Nerus87** [comment]
I think it's stuck on updated words, I'll turn it in tomorrow morning before work.

Variable `max_allowed_packet` was too small 1M so I change it to 10M
