### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by LuigiElleBalotta** [CypherCore/CypherCore#6]
i can't login with the client. I use Arctium launcher (latest release). I updated also the field in auth.realmlist.gamebuild to 25549.

I use the correct email + password.

What do i do:
1. Launch client with Arctium launcher
2. at login form i write my credentials
3. I select the realm
4. Realm popup closes and i'm again at login form
5. In worldserver console i read this: "WorldSocket.HandleAuthSession: Authentication failed for account: 2 ('2#1') address: 127.0.0.1"

This is the function that write that error
http://luigiellebalotta.altervista.org/privatebin/?e0f5f45ebf9bfc68#+AarUTIHTbBI51PZgpsonWSwUg25sigxLF74mHF3+eg=

**Comment by hondacrx** [comment]
you need to make sure the auto updater is working to update auth DB you need to use the sql that are in the repo  and not TC ones

**Comment by LuigiElleBalotta** [comment]
I am using cyphercore basefiles

**Comment by hondacrx** [comment]
blizz changed the login stuff, will be a while till its updated

**Comment by hondacrx** [comment]
Fixed in https://github.com/CypherCore/CypherCore/commit/4ed0efb83014b58d3ecf19cdda4781448f996f53
